trigger: none

variables:
- name: devEnvironment
  value: dev

resources:
  pipelines:
  - pipeline: cipipeline # TODO: Update with the name of your CI pipeline & apply it to line 71
    source: 'CI Pipeline'
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  # IaC variables
  variables:
  - template: yaml-templates/pipeline-vars.yml

  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceSettings@1
            displayName: Azure App Service Settings
            inputs:
              azureSubscription: 'LAStandard'
              appName: '$(logicAppName)'
              resourceGroupName: '$(resourceGroupName)'
              
              # TODO: Add the app settings for the connections 
            
              appSettings: |
                [
                  {
                    "name": "serviceBus_connectionString",
                    "value": "test",
                    "slotSetting": false
                    },
                    {
                    "name": "azureFunctionOperation_functionAppKey",
                    "value": "test",
                    "slotSetting": false
                    },
                    {
                    "name": "azureFunctionOperation_functionResourceURI",
                    "value": "test",
                    "slotSetting": false
                    },
                    {
                    "name": "azureFunctionOperation_functionTriggerURI",
                    "value": "test",
                    "slotSetting": false
                    }
                    
                ]
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:              
              azureSubscription: 'LAStandard' # TODO: Fill in with the GUID of your Azure service connection created on your Azure Devops
              appType: 'functionApp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              deploymentMethod: 'zipDeploy'