trigger: none

variables:
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: dev

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  jobs:
  - job: CopyFiles
    displayName: 'publish ARM files to artifact'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)/src/devops/arm-templates'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: yaml-templates/pipeline-vars.yml
  jobs:
  - template: templates/template-iac-logicapp.yml
    parameters:
      environment: $(devEnvironment)      
      serviceConnection: 'LAStandard' # TODO: Fill in with the GUID of your Azure service connection created on your Azure Devops