# IaC variables

variables:

  projectName: 'projstdlogicapp'
  env: 'dev'

  # Resource Group
  resourceGroupLocation: 'westeurope'
  resourceGroupName: 'rg-we-$(projectName)-$(env)'

  # Storage - make sure this is unique!
  storageName: 'sa$(projectName)$(env)'
  appServicePlanName: 'asp$(projectName)$(env)'

  #  Logic App
  logicAppName: 'la-we-$(projectName)-$(env)'

  # API Connections - if you change this name, you must change the reference in workflow.json
  blobConnectionName: 'azureblob'

  # Project artifacts
  logicAppCIArtifactName: 'logicapp_publish_artifact'
